# Generated by Django 4.2.27 on 2026-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_location_update_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
