# Generated by Django 4.2.27 on 2025-12-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastereport',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('construction', 'Construction'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous'), ('other', 'Other')], default='low', max_length=20),
            preserve_default=False,
        ),
    ]
