# Generated by Django 4.2.27 on 2025-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_wastereport_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='location_source',
            field=models.CharField(choices=[('auto', 'Auto-detected'), ('manual', 'Manually Selected')], default='auto', max_length=10),
        ),
    ]
