# Generated by Django 4.2.27 on 2026-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_wastereport_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
