# Generated by Django 4.2.27 on 2026-01-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_wastereport_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
