# Generated by Django 4.2.27 on 2026-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_wastereport_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
