# Generated by Django 4.2.27 on 2026-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_wastereport_rating_wastereport_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_waste_images/'),
        ),
    ]
