# Generated by Django 4.2.27 on 2026-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_wastereport_resolved_image_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_images/'),
        ),
    ]
