# Generated by Django 4.2.27 on 2026-01-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_wastereport_resolved_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='resolved_image',
        ),
    ]
