# Generated by Django 4.2.27 on 2026-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_wastereport_resolved_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='location_source',
            field=models.CharField(choices=[('auto', 'Auto-detected'), ('manual', 'Manually Selected'), ('gps-high-accuracy', 'High Accuracy GPS'), ('gps-low-accuracy', 'Low Accuracy GPS')], default='auto', max_length=20),
        ),
    ]
