# Generated by Django 4.2.27 on 2026-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_wastereport_location_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('metal', 'Metal'), ('glass', 'Glass'), ('paper', 'Paper'), ('electronic', 'Electronic'), ('construction', 'Construction'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous'), ('other', 'Other')], max_length=20),
        ),
    ]
