# Generated by Django 4.2.27 on 2026-01-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_wastereport_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_images/'),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('metal', 'Metal'), ('glass', 'Glass'), ('paper', 'Paper'), ('electronic', 'Electronic'), ('construction', 'Construction'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
